import type { BlogPost } from "@/lib/blog";

// New EN posts (2026-10-01). Internal links are written [anchor](/en/blog/slug)
// inside paragraphs; BlogPostPage turns them into links.
export const newPostsEn: BlogPost[] = [
  {
    id: "seo-vs-geo-2026",
    slug: "seo-vs-geo-online-visibility-2026",
    title: "SEO vs GEO: How Is Online Visibility Changing in 2026?",
    date: "2026-10-01",
    dateLabel: "October 1, 2026",
    excerpt:
      "SEO isn't going away, it is being joined by GEO: being cited in an AI's answer rather than merely ranked in a list. What changes, what stays, and where a small business should start.",
    tags: ["SEO", "GEO", "Visibility"],
    sections: [
      {
        h: "Introduction",
        p: [
          "For twenty years, being visible online meant one thing: appearing as high as possible in Google's list of links. In 2026, a growing share of searches ends differently: with a written answer and a few cited sources, produced by Google AI Overviews, ChatGPT, Perplexity or Gemini. The user no longer necessarily clicks, they read the summary.",
          "Two acronyms now compete in conversations: SEO (Search Engine Optimization) and GEO (Generative Engine Optimization). This article explains how they really differ, what they share, and how a small business can move on both without doubling its work. If GEO is new to you, our guide on [making your business visible in AI search engines](/en/blog/how-to-make-your-business-visible-in-ai-search-engines) lays the groundwork.",
        ],
      },
      {
        h: "What is the difference between SEO and GEO?",
        p: [
          "SEO aims to get a page ranked among a search engine's results. Success is a position, then a click. GEO aims to get a piece of content, or a brand, cited in an answer generated by an AI. Success is a mention, with or without a click. In the first case you compete for a place in a list; in the second, for a sentence in a text.",
          "This difference changes the unit of work. In SEO, you optimise a whole page around a query. In GEO, the AI splits pages into passages and extracts a chunk of one to two hundred words that answers the question directly. A clear, self-contained, factual paragraph therefore matters more than a long text that ranks well but is diffuse.",
          "The two disciplines are not opposed, though. Most AI engines rely on classic search indexes to find their sources: a poorly indexed or poorly ranked site has little chance of being cited. GEO does not replace SEO, it stacks on top of it.",
        ],
      },
      {
        h: "What stays the same between the two?",
        p: [
          "The foundations do not move: a fast, HTTPS-accessible, well-structured site with no indexing errors and useful content written by someone who knows the subject. No GEO trick compensates for a site that robots cannot read.",
          "Authority also remains central. Classic engines rely on inbound links, AI engines on brand mentions, meaning how often a business is cited, consistently, by independent sources: directories, trade press, forums, customer reviews. In both cases, reputation is built off your own site, over time.",
          "Quality content finally remains the common base. An article that answers a real question precisely, with lived examples and verifiable figures, serves both logics. We have seen it on our own sites: articles that are too general and follow the news pile up impressions in results without producing a single click, because content that answers no precise question attracts neither readers nor customers.",
            "A practical point, often neglected: speed and mobile display. A large share of searches, classic and conversational, happens on phones. A page that is slow or hard to read on a small screen loses readers before they reach the answer, and engines factor it into their quality criteria.",
        ],
      },
      {
        h: "What does GEO change in how you write?",
        p: [
          "First change: the answer first. A section should start with the direct answer, in one or two sentences, before expanding. An AI trying to answer 'how much does a showcase website cost?' will prefer the passage that states a range in the first line over one that opens with three paragraphs of context.",
          "Second change: headings phrased as real questions. People now ask AIs in full sentences, and a heading that echoes the question as asked eases matching. This explains the question form of most titles in this log.",
          "Third change: attributable facts. Sourced figures, crisp definitions, proper names, dates: passages rich in verifiable elements are easier to cite than general talk. Research on the subject has shown that adding statistics, quotes and sources to a text clearly increased its likelihood of being picked up by a generative engine, by several tens of percent in their experiments. The effect depends on the engine and topic, but the direction is constant: precision pays.",
        ],
      },
      {
        h: "How do you measure visibility in the AI era?",
        p: [
          "In SEO, Search Console gives impressions, clicks and positions. For GEO there is no equivalent official tool, and that is a real difficulty: a business can be cited without any click being recorded. Three practices give a clear picture on no budget.",
          "The first is to test, once a month, about ten questions your customers would really ask on ChatGPT, Gemini and Perplexity, and note who is cited. The second is to track in your analytics tool the traffic from chatgpt.com or perplexity.ai, small but telling. The third is to watch, in Search Console, queries phrased as questions: their growth shows your content fits the expected format.",
          "Do not expect results within days. Indexes and models update at their own pace, and a rewritten page can take weeks to appear in an answer. Measure by quarter rather than by week, and keep a simple table: date, question, engine, result.",
        ],
      },
      {
        h: "Where should a small business start?",
        p: [
          "Start by checking the basics, because that is where the quickest gains hide: is the site indexed, does robots.txt allow the useful bots, are key pages readable without JavaScript? A one-hour check often fixes blockages nobody had seen.",
          "Then rewrite your key pages in question-and-answer format: one page per service, with a question heading, a direct answer, indicative prices and a short FAQ. Add structured data, which helps engines understand who you are and what you offer. Finally, work on your presence off the site: an up-to-date business profile, professional directories, customer reviews, a few mentions in local or trade press.",
          "Rhythm matters less than consistency. One useful article a month that answers a real customer question precisely beats four generic texts. To choose topics, start from the questions your prospects already ask you: that is the best indicator of what AIs will be asked to answer for them.",
            "Take a service page as an example. Instead of a title such as 'Our services', write 'How much does a showcase website cost?', answer in the very first sentence with a price range, explain what makes it vary, then add three or four frequent questions. That single page serves classic search, which finds its query there, and AIs, which find a passage ready to cite.",
        ],
      },
      {
        h: "What mistakes should you avoid when starting with GEO?",
        p: [
            "The first mistake is believing GEO boils down to a technical trick. You regularly read that adding a particular file at the site root is enough to be cited by AIs. No major engine has shown that such a file alone changes any result: it is always content, structure and reputation that make the difference. Technical shortcuts do not replace a useful site.",
            "The second mistake is writing for machines. A text stuffed with repeated phrasing and artificial questions is quickly spotted and serves nobody. The right test is simple: reread your page as a customer in a hurry. If it clearly answers their question, an AI will know how to use it; if not, no optimisation will save it.",
            "The third mistake is trusting those who guarantee results. Nobody controls what ChatGPT or Gemini choose to cite, and engines regularly change how they work. A serious provider talks about probabilities and method, not first-place promises. Beware of the opposite too: dropping SEO 'because everything goes through AI' would be a costly mistake, since AIs still rely heavily on it.",
        ],
      },
      {
        h: "Conclusion",
        p: [
          "SEO and GEO do not exclude each other: the first ensures you are found and credible, the second that you are picked up when an AI answers in the user's place. The sensible strategy for a small business is to consolidate its SEO foundations, then adapt its content to the format AIs can extract: direct answer, question as heading, verifiable facts.",
          "If you want an outside view of your site's visibility, that is precisely where La Fabrik Numérique supports businesses. You can also read our article on how to [get your app featured in AI search results](/en/blog/how-to-get-your-app-featured-in-ai-search-results), or write to us from the [contact page](/en#contact).",
        ],
      },
    ],
    links: [
      {
        label: "Making your business visible in AI search engines",
        url: "/en/blog/how-to-make-your-business-visible-in-ai-search-engines",
      },
      {
        label: "Why a SaaS can have users but no sales",
        url: "/en/blog/why-a-saas-has-users-but-no-sales",
      },
    ],
  },
  {
    id: "saas-users-no-sales",
    slug: "why-a-saas-has-users-but-no-sales",
    title: "Why Can a SaaS Have Users but No Sales?",
    date: "2026-10-01",
    dateLabel: "October 1, 2026",
    excerpt:
      "Downloads, traffic, clicks on 'buy' and yet zero sales: a field report on our own software, with the real numbers and the diagnostic method we apply since.",
    tags: ["SaaS", "Lessons learned", "Monetization"],
    sections: [
      {
        h: "Introduction",
        p: [
          "On September 29, 2026, VoxCut passed 1,000 cumulative downloads across all channels: exactly 1,006, including 579 via GitHub and 282 via Google Play. But those downloads did not turn into sales in proportion to the apparent interest. Another of our products, VidScope, received about 83 unique visitors in ten days for three analyses run and zero orders.",
          "This situation is more common than people admit: having users does not mean having customers. This article tells what our own numbers taught us, and proposes a method to find, in order, where a software funnel gets stuck. It is not a theoretical guide: every case comes from our products.",
        ],
      },
      {
        h: "Do downloads really measure interest in a product?",
        p: [
          "No, or only partially. A download measures a moment's curiosity: someone saw a listing, found the idea interesting, clicked. It says nothing about real need, frequency of use or willingness to pay. A product downloaded a thousand times by the curious is worth less than one used every week by ten professionals.",
          "On VoxCut Android, the 14-day analysis showed 169 installs, 96% of onboarding completed, and 118 users who saw the purchase screen. Activation figures were good: the product worked and people used it. Yet no purchase was confirmed. Interest existed, but it did not convert, and the cause was not the one you would have guessed.",
          "First habit to adopt: stop looking at the total, and look at the step where users disappear. A funnel is read in percentages from one step to the next, not in cumulative volume.",
            "Origin matters too. On VoxCut, 579 downloads come from GitHub, 282 from Google Play, 104 from Softpedia, 36 from the Microsoft Store and 5 from the Snap Store. These channels do not attract the same audiences: someone downloading an executable from a code repository is not looking for the same thing as someone installing an app from their phone. Adding these figures up gives a flattering total, but turning it into an average conversion rate makes no sense.",
        ],
      },
      {
        h: "Where does the funnel break: technology, offer or audience?",
        p: [
          "In our case, the first blockage was purely technical. Over 14 days, 37 clicks on the buy button had been recorded, about 10% of installs, which is a real intent signal. But several of those clicks ended in an error: the product was not loaded from the store, or its identifier did not match. Customers ready to pay simply could not.",
          "Before touching price or message, you must therefore check that the purchase path works, end to end, on a real device. It is a boring check, but it should come first: optimising a leaking funnel is pointless.",
          "Once the technology is clean, two other causes remain. The offer: does the free version already give users what they want, or is the difference with the paid version blurry? And the audience: do arriving visitors actually have the need the product solves? For VidScope, much of the traffic landed on AI news articles, far from what the tool does. Lots of visits, no purchase intent.",
        ],
      },
      {
        h: "Why doesn't traffic turn into sales?",
        p: [
          "Traffic matters less than its fit. On VidScope, Search Console showed 227 impressions and 3 clicks over 28 days, with queries unrelated to the product. A send of 115 prospecting emails brought only 3 measured visitors. It was not a problem of volume of actions: we had listed on some fifteen directories, written articles, commented on videos. It was a problem of channel choice.",
          "There is also a structural hypothesis the numbers do not immediately show: occasional use. A YouTube viewer needs a tool like VidScope once in a while, so has no reason to pay. A technical content creator needs it for every video. Same product, two usage frequencies, two very different willingness to pay.",
          "One last thing to examine: the promise. A home page that speaks to everyone convinces no one. We removed unfounded phrases from VidScope's page ('our community', 'join the creators') to keep only what the tool really does: it makes the product less spectacular, but more credible.",
            "Keep in mind, finally, that time plays a part. A recent product has no word of mouth, reviews or track record yet. The first weeks mostly serve to check the foundations hold: the purchase path works, the promise is understood, the right people arrive. Sales come after, rarely before.",
        ],
      },
      {
        h: "How do you diagnose your own case, step by step?",
        p: [
          "Here is the method we now apply, in order. One: measure the funnel step by step (visit, trial, core use, purchase screen, buy click, purchase) with the same sources each time, isolating each product if several share an analytics tool. Two: check the purchase path on a real device, in real conditions.",
          "Three: look at who actually arrives. If traffic comes from off-topic articles, or from a directory whose audience lacks the need, it is an audience problem, not a product one. Four: question the offer. If the free tier covers the need, nobody will pay, which is good news about the product's usefulness but bad about its model. Five: talk to real users, even five, rather than adding another marketing action.",
          "One rule has spared us mistakes: do not conclude on small numbers. With three analyses or forty visitors, no trend is reliable. The right answer is then to document, wait for a more significant sample, and change one parameter at a time to know what produced the effect.",
        ],
      },
      {
        h: "What should you change first to turn users into customers?",
        p: [
          "In the order of effectiveness we observed: fix what technically prevents buying, align the promise with real use, then think about price positioning and when the purchase screen appears. Showing the paid offer right after the user has seen a concrete result, such as a first exported file, converts better than showing it when the app opens.",
          "You must also accept an uncomfortable conclusion: sometimes the product really is useful, but not to those who find it. It is then better to narrow the audience than to multiply channels. Choosing the right audience weighs more than ten extra directories. The price question itself is covered in our article on [how to price a SaaS product](/en/blog/how-to-price-a-saas-product).",
        ],
      },
      {
        h: "Which signals should you check before concluding a product won't sell?",
        p: [
            "The first signal is the intent ratio. That 10% of installs lead to a buy click is rather encouraging for a small tool: it shows people understand the offer and are tempted. A product of no interest does not reach that figure. It is precisely because this signal existed that we had to look for the leak in the funnel rather than question the idea.",
            "The second signal is repeat use. A tool you use once then forget will sell only if it solves a costly problem. Look at how many users come back a second, then a third time: if almost nobody does, the problem lies in the need or the experience, not the price.",
            "The third signal is qualitative, and the hardest to hear: feedback from people who know the subject. A tester told us bluntly that one of our products was not worth paying for as it stood. That kind of feedback stings, but it is worth ten dashboards, because it says why. Note it, cross-check it against your numbers, and treat it as a hypothesis to test, not a verdict.",
        ],
      },
      {
        h: "Conclusion",
        p: [
          "Users without sales do not mean a failed product, but a funnel to be read step by step: technology first, audience next, offer last. The approach is the same we apply to our clients' projects, and rests on a simple principle: measure before you change.",
          "If you are building software and your numbers look like ours, an outside look at your funnel can save weeks. You can also read our comparison of [custom tools and SaaS](/en/blog/custom-tool-vs-saas-real-cost-over-3-years), or contact us from the [contact page](/en#contact).",
        ],
      },
    ],
    links: [
      {
        label: "How to price a SaaS product",
        url: "/en/blog/how-to-price-a-saas-product",
      },
      {
        label: "Discover VoxCut → voxcutpro.com",
        url: "https://voxcutpro.com",
      },
    ],
  },
  {
    id: "saas-pricing",
    slug: "how-to-price-a-saas-product",
    title: "How Do You Price a SaaS Product?",
    date: "2026-10-01",
    dateLabel: "October 1, 2026",
    excerpt:
      "Subscription, one-time payment, freemium or trial: how to choose a model and a price for a small piece of software. Method and examples from our own products' price grids.",
    tags: ["SaaS", "Pricing", "Lessons learned"],
    sections: [
      {
        h: "Introduction",
        p: [
          "Setting a software price is one of the most uncomfortable decisions of a launch: too low and you cannot live off your product; too high and nobody tries it. And contrary to a common belief, there is no formula: benchmarks give landmarks, never a number.",
          "We ourselves changed our grids several times. VoxCut Android went from €11.99 to €14.99 as a one-time payment; VidScope reworked four tiers; VectorPop is €39 for life. This article shares the method that served us, rather than a promise of an ideal price. It complements our analysis of [why a SaaS can have users but no sales](/en/blog/why-a-saas-has-users-but-no-sales).",
        ],
      },
      {
        h: "Should you choose a subscription or a one-time payment?",
        p: [
          "The answer depends on frequency of use and on what you cost to run. A tool used every week that relies on a paid online service (servers, an AI API, storage) justifies a subscription: your costs recur, so should your revenue. A tool used three times a year that runs entirely on the user's computer lends itself poorly to a subscription: nobody wants to pay monthly for an occasional need.",
          "That reasoning led us to a one-time payment for VectorPop, InOneShot and Nyctale: the maths is simple for the user, and 'no subscription' is a real differentiator against competing services billed monthly. Our article on the [real cost of a custom tool versus SaaS over three years](/en/blog/custom-tool-vs-saas-real-cost-over-3-years) details that calculation from the buyer's side.",
          "Conversely, VidScope, which uses AI at each analysis, mixes pay-per-use tiers, a monthly subscription and a lifetime purchase capped by a monthly quota. Each model matches a profile: the occasional user, the regular one, the one who wants to pay once.",
        ],
      },
      {
        h: "How do you estimate what the product is worth to the customer?",
        p: [
          "Start from value, not from your costs. Ask what the customer saves or gains: how much time, money, errors? A tool that spares a professional billing €50 an hour one hour of manual work a week earns them more than €2,500 a year, and a €39 price then looks trivial. Conversely, a convenience tool for an individual must stay close to the price of a coffee or a meal.",
          "Then look at the alternatives, including free and manual ones. A small program's real competitor is often the spreadsheet, open-source software or work done by hand. If your price is several times what the alternative costs without an obvious time gain, it will be hard to defend.",
          "Finally, get real potential customers talking. Ask five people at what price they would say 'that is too expensive' and at what price they would doubt the quality. The range between the two is your ground, and it is almost always narrower than you imagine.",
            "Think about how the price is presented too. To individuals, show the price including taxes, which is what they compare. To professionals, the price excluding tax is the norm. A price shown the wrong way can look 20% dearer or cheaper than reality, and create a misunderstanding at payment time.",
        ],
      },
      {
        h: "Freemium, free trial or demo: which mechanism?",
        p: [
          "Free exists to let people see the value before being asked to pay, but it must be calibrated. If the free version covers the whole need, nobody will upgrade; if it is too limited, nobody sees the point. On VectorPop, vectorization, presets and preview stay unlimited, and only export is counted, with five exports included to test real files: the user sees the result, and pays when they want to take it away regularly or in high quality.",
          "A time-limited trial suits products whose value appears over time, such as a management tool. Freemium suits occasional-use products where everyone should be able to test without commitment. A demo, finally, mostly suits software sold to businesses, which want to see before buying.",
          "Whatever the mechanism, when you offer to charge matters more than the design of the offer. Field experience converges: proposing purchase right after the user got a concrete result converts better than showing it on opening. Show the value first, ask afterwards.",
        ],
      },
      {
        h: "How do you structure a readable price grid?",
        p: [
          "The fewer tiers the better. Three or four offers are plenty, with a recommended one highlighted. Each tier must answer an identifiable profile, not an artificial variation in quantity. A grid that forces three re-reads to understand what you get drives people away as much as a price that is too high.",
          "Be consistent everywhere. A price that differs between the home page, the promotional banner and the checkout page destroys trust in seconds. We have had the case: a banner announced a launch offer at €79 while the pricing card showed €149. The visitor does not know which is true, and chooses not to buy.",
          "Beware of permanent discounts too. A launch offer must have a real limit, in number or date, otherwise it simply becomes the price, and buyers know it. Conversely, a price rise announced in advance, from a given date, creates a legitimate sense of urgency.",
            "A readability tip: bring the price down to a meaningful unit. For a €39 lifetime tool, comparing with the cost of an equivalent monthly subscription over two years makes the saving obvious without needing to boast about it. The comparison must stay honest: cite real competitors, with their real, verified prices.",
        ],
      },
      {
        h: "When should you change your price?",
        p: [
          "You change a price when you have data, not when you doubt. With no sales, lowering is tempting, but it is not always the right answer: if the purchase path is broken or the audience poorly targeted, a lower price will fix nothing. Check these two points before touching the number.",
          "If buy clicks are many but payments rare, look at price and payment: hidden fees, extra steps, unexpected currency. If visitors do not even click on the offer, the problem is more in the promise or positioning. Change one parameter at a time to know what acts.",
          "Finally, once the price is validated, do not change it without reason. A carefully reworked grid beats a series of nervous adjustments: it gives customers a stable message and you a stable frame for measuring.",
        ],
      },
      {
        h: "What pricing mistakes did we make?",
        p: [
            "The first was letting a price move several times in the same day. During the VoxCut Android decision, the figure swung between €14.99 and €19.99 before settling, after a debate that nearly led to an inconsistency between the annual and lifetime offers. The price finally chosen, €14.99 one-time, was the right one. But deciding fast, with no time to step back, is a risk: write down the options, sleep on it, decide the next day.",
            "The second is the inconsistency between pages, mentioned above. It seems anecdotal, but it blurs trust at the most sensitive moment. After a price change, always walk through every page where it appears: home, price grid, banner, checkout page, app-store listing.",
            "The third was opening the free tier too widely. On VoxCut, a free version with unlimited exports had been considered, before we questioned it the same day: it opened the floodgates and left no reason to go paid. Free should show the value, not deliver it entirely. That is what led us to VectorPop's free export quota.",
        ],
      },
      {
        h: "Conclusion",
        p: [
          "Setting a software price means choosing a model consistent with frequency of use, anchoring the number in customer value, calibrating the free tier, then keeping a simple and stable grid. Market benchmarks help, but only your own data will tell you whether you are right.",
          "If you are preparing to launch software or a SaaS, La Fabrik Numérique can help frame the offer as well as the technical build. Let us talk from the [contact page](/en#contact), or first read our article on the difference between a [showcase website and a web app](/en/blog/showcase-website-or-web-app-how-to-choose).",
        ],
      },
    ],
    links: [
      {
        label: "Why a SaaS can have users but no sales",
        url: "/en/blog/why-a-saas-has-users-but-no-sales",
      },
      {
        label: "Custom tool or SaaS: the real cost over 3 years",
        url: "/en/blog/custom-tool-vs-saas-real-cost-over-3-years",
      },
    ],
  },
  {
    id: "automate-sme-tasks-ai",
    slug: "automate-repetitive-sme-tasks-with-ai",
    title: "How Can a Small Business Automate Repetitive Tasks with AI?",
    date: "2026-10-01",
    dateLabel: "October 1, 2026",
    excerpt:
      "Which tasks to automate first, when AI is useful and when a simple script is enough, how to limit risk. A concrete method, with examples from our own tools.",
    tags: ["AI", "Automation", "SMB"],
    sections: [
      {
        h: "Introduction",
        p: [
          "In many small businesses, a large share of time goes into tasks that look alike from one day to the next: re-keying data from one document to another, producing near-identical quotes or certificates, sorting messages, chasing customers. None is hard, all are time-consuming, and that is exactly what a tool can absorb.",
          "Artificial intelligence adds new possibilities, such as reading an unstructured document or drafting a text, but it is not always the right answer. This article offers a method to choose what to automate, with which kind of tool, and how to do it without taking needless risk. It draws on tools we built for our own use, as we explain in the article [Why we build our own tools](/en/blog/why-we-build-our-own-tools).",
        ],
      },
      {
        h: "Which tasks should a small business automate first?",
        p: [
          "Good candidates share three traits: they repeat often, they follow fairly stable rules, and a mistake is cheap or easy to recover from. Producing fifty certificates from a table, renaming and filing documents, extracting amounts from invoices, preparing reminders: these are tasks you can hand to a tool without the business suffering.",
          "Conversely, avoid starting with what is rare, highly variable or high-stakes: negotiation, credit decisions, sensitive communication. Automation costs more than it brings there, and a mistake is visible.",
          "To spot your candidates, note on a sheet for one week every repetitive task and the time it takes. Then rank them by monthly hours. The top three lines of that table are almost always where the gain is clearest.",
            "An order of magnitude helps you decide. A twenty-minute task repeated every working day adds up to more than seventy hours a year, nearly two weeks of work. Many managers discover, by adding up this way, that small tasks they judged harmless weigh far more than the project they kept putting off. A telling example: [editing a podcast, where automatic silence removal](/en/blog/how-to-remove-silences-from-a-podcast) saves several hours per episode.",
        ],
      },
      {
        h: "AI, classic automation or a script: which to choose?",
        p: [
          "The current reflex is to hand everything to AI. It is often excessive. When a task follows precise rules, a script or classic automation tool is faster, cheaper and above all predictable: it always does the same thing. Generative AI brings flexibility but also variability, and you must check its results.",
          "AI becomes relevant when the input is loosely structured: a freely written email, a scanned PDF, a description in natural language. It can then extract information or suggest wording where a fixed rule would fail. The most robust combination is often hybrid: AI understands or drafts, a classic tool executes, and a person validates.",
          "Take a concrete example. Generating hundreds of personalised documents from an Excel table needs no AI: a well-built mail merge is enough, as we explain in our article on [generating PDFs from Excel](/en/blog/generate-pdfs-from-excel). Reading free-form letters to pull out useful information, however, justifies a language model.",
        ],
      },
      {
        h: "How do you set up automation without taking risks?",
        p: [
          "Start small, on one process, with a person validating each result at first. Test on about twenty real cases before widening: you will quickly see the situations the tool handles poorly, and can fix them before it costs anything.",
          "Always keep a record of what the tool did, and a simple way to go back. An automation that changes data without a log is a risk, even if it works well. Also plan a fallback procedure: if the tool breaks, how is the work done by hand?",
          "Finally, measure the real gain. Compare time spent before and after over a full month, including checking time, often forgotten. An automation that saves ten hours but costs six in checks only gains four, and you need to know it.",
            "Finally, document what you have set up, even in a few lines: what the tool does, where the data is, who monitors it. When the person who designed it is away, or when it has to evolve six months later, this note saves you from rediscovering everything.",
        ],
      },
      {
        h: "What about sensitive data and GDPR?",
        p: [
          "This is the question that stops the most managers, rightly. Sending an online service documents containing customer names, contact details or health data raises a real confidentiality problem, especially as terms of use and retention periods vary from one service to another. Check where data is processed, whether it is used to train models, and what the contract provides.",
          "When data is sensitive, the simplest solution is often to process it locally: a tool installed on the computer that sends nothing over the internet removes the problem at the root. That is the choice we made for InOneShot, which generates documents from data that never leaves the machine, and for VectorPop, whose images stay on the user's computer.",
          "In every case, limit transmitted data to what is strictly necessary, pseudonymise when possible, and inform the people concerned if their data goes through a provider. A simple register of automated processing will spare you many questions later.",
        ],
      },
      {
        h: "When should you call a developer?",
        p: [
          "Many simple automations can be set up without a developer, with consumer tools or features already in your software. A developer becomes useful when the process is specific to your trade, links several programs that do not talk to each other, or must run reliably every day with nobody watching.",
          "In that case, a well-scoped custom tool often costs less over time than a stack of subscriptions, as our analysis of the [real cost of a custom tool over three years](/en/blog/custom-tool-vs-saas-real-cost-over-3-years) shows. The key point is to scope the need before coding: which task, what volumes, which exceptions, who validates.",
        ],
      },
      {
        h: "What are some concrete examples in a small business?",
        p: [
            "First example: repetitive documents. Certificates, quotes, delivery notes, invitations: all start from a template and a few data points that change. A generation tool produces the fifty documents of a session in minutes, where manual entry takes half a day and lets typos through. That is InOneShot's ground, which we designed for training organisations.",
            "Second example: sorting and extraction. An inbox receiving requests of varied kinds, invoices to key in, files to sort: AI can read free text and pull out the subject, amount or urgency, which a classic tool then files in the right place. A human checks the doubtful cases, which is still far faster than handling everything by hand.",
            "Third example: reminders and reports. Chasing unpaid invoices, telling a customer their file is progressing, compiling a weekly update: these messages follow simple rules and benefit from going out at a fixed time. AI can draft a personalised version, and the person only has to read and send. You keep control of sending, essential when you are talking to a customer.",
        ],
      },
      {
        h: "Conclusion",
        p: [
          "Automating a small business's repetitive tasks with AI takes less technology than method: spot frequent, stable tasks, pick the right tool, whether a script or a language model, test on few cases, measure the real gain and protect the data.",
          "If you have a repetitive task that deserves this treatment, La Fabrik Numérique builds custom tools for small businesses. Write to us from the [contact page](/en#contact), or first discover how to [choose between a showcase website and a web app](/en/blog/showcase-website-or-web-app-how-to-choose).",
        ],
      },
    ],
    links: [
      {
        label: "Generating PDFs from Excel",
        url: "/en/blog/generate-pdfs-from-excel",
      },
      {
        label: "Discover InOneShot → inoneshot.fr",
        url: "https://inoneshot.fr",
      },
    ],
  },
];
